Add search and save for the remaining tables
fpdcc/ccfp-asset-dashboard pull request #128
Opened 2022-02-15 16:22 UTC by smcalilly

## Overview
Adds search for the remaining tables. Closes #118.

Other changes include:
- DB migration for `LocalAsset` model to accommodate for when the `asset_id` is a charfield instead of an integer. This is required because the `PicnicGroves` fpd_id is a charfield.
- Another DB migration for `LocalAsset` model to allow null and blank `asset_id` fields. This field was meant to save the `fpd_uid` but in testing this PR, I found an edge case where sometimes that field is null.
  - Also had to create a `NullableCharField` in the `BaseLocalAssetSerializer` so we could save this field.
  - The discovery of this edge case led to a discovery of improper 400 error handling when submitting a post request via ajax, so I added better error handling for that.
- Added a popup to the asset geometries in the map.
- For the `ParkingLots` model, changed the table to search the `"acer"."parking_lots_union_mv"` and changed the fields to match that materialized view.

### Notes
This searches all of the tables that we've discussed with Garret. If we need to fine tune the columns we search, it will be as simple as adding the desired columns to @hancush's clever [`Search` subclass](https://github.com/fpdcc/ccfp-asset-dashboard/blob/757805367f3452f8de4ec49be908084011e11e3d/asset_dashboard/models.py#L381) solution. That subclass works in unison with [the `AssetViewSet's `get_queryset` method](https://github.com/fpdcc/ccfp-asset-dashboard/blob/757805367f3452f8de4ec49be908084011e11e3d/asset_dashboard/endpoints.py#L85).

## Testing Instructions
- visit review app: https://ccfp-asset-d-remaining--jg5dia.herokuapp.com/
- login with the `ccfp-asset-dashboard test user` credentials in lastpass
- go to the asset map tool
- search and save these types of assets:
  - Points of Interest
  - Picnic Groves
  - Parking Lots
  - Signage
- you can test the NullableCharField in the `BaseLocalAssetSerializer` by searching those asset types with the text "red". that search should return some assets where that field null. you should be able to save the assets when they have a identifier field.

2022-02-15 16:26 UTC, smcalilly commented on asset_dashboard/models.py
> +        db_table = '"acer"."parking_lots_union_mv"'
query this materialized view in the `acer` table instead of the `quercus` table.

2022-02-16 14:29 UTC, fgregg requested changes
looks good!

2022-02-16 14:29 UTC, fgregg commented on asset_dashboard/migrations/0026_auto_20220207_2145.py
> +            field=models.CharField(max_length=1000000),
if the charfield is that long, we should use a textfield

2022-02-16 14:29 UTC, fgregg commented on asset_dashboard/migrations/0027_auto_20220215_1707.py
> +            field=models.CharField(blank=True, max_length=1000000, null=True),
ditto on textfield

2022-02-16 14:29 UTC, fgregg commented on asset_dashboard/models.py
> +    asset_id = models.CharField(max_length=1000000, null=True, blank=True)
text field

2022-02-16 14:29 UTC, fgregg commented on asset_dashboard/models.py
> -    """Parking lot polygons, for all public and non-public lots."""
why did we lose this doc string?

2022-02-16 17:17 UTC, smcalilly commented on asset_dashboard/models.py
> -    """Parking lot polygons, for all public and non-public lots."""
oops! added back here: 2363933

2022-02-16 17:50 UTC, smcalilly commented on asset_dashboard/models.py
> +    asset_id = models.CharField(max_length=1000000, null=True, blank=True)
changed here: b1f7117

2022-02-16 17:51 UTC, smcalilly commented
@fgregg this is ready for re-review. you can test the review app at this new instance: https://ccfp-asset-d-remaining--jg5dia.herokuapp.com/

2022-02-24 17:10 UTC, fgregg approved these changes
looks good @smcalilly

2022-02-25 15:33 UTC, merged